# Generated by Django 6.0.3 on 2026-03-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_booking_expiry_voice_notes'),
        ('fitness', '0006_new_features'),
    ]

    operations = [
    ]
