# Generated by Django 6.0.3 on 2026-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_merge_20260327_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='voice_note',
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(),
        ),
    ]
