# Generated by Django 5.2.14 on 2026-05-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_alter_fitnessgoal_id_alter_weightlog_id'),
        ('fitness', '0013_improvements'),
    ]

    operations = [
    ]
