# Generated by Django 5.2.14 on 2026-05-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_merge_20260524_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Session rate in PHP (0 = free with membership)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='image_url',
            field=models.URLField(blank=True, help_text='Demo image URL for this exercise'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or demo video URL for this exercise'),
        ),
    ]
